### PR TITLE
Fix data loss bug

### PR DESCRIPTION
**Pull request by danielbeardsley**
Previously, hits received during a flush (after the /endpoint
request was sent, but before hearing the response) would be thrown
away because reset() was called when the response came back.

Now, we reset the data store right when we serialize it
(no data loss) and under normal circumstances, do nothing.
If there's an error during flush, we merge the old data store
with the new one.

I've also improved the test and changed flushing to consider
a non-200 response from the server as a failure.

### CODE REVIEW

**Comment by jonigl** [comment]
This PR it's working perfect and resolved the data loss bug! Thanks a lot, I know this project remains inactive since 2017 but I think it's important to highlight this solution :)

**Comment by jashkenas** [comment]
Thanks for this patch (and for the bump, @jonigl)!

I've merged and released it, with a few tweaks, as 0.1.5:

https://github.com/documentcloud/pixel-ping/commit/0255ed909b7e36f6507187b42fe8fb388bf7bd93#diff-25c84ee22f3313d5c3644f0d96ff4850

**Comment by jonigl** [comment]
Hey @jashkenas thanks to you for this new version!

**Comment by danielbeardsley** [comment]
FYI, I realized I hadn't used this pull in production until now. We just tried it and it exposed another bug (not in this code). See #14

**Pull request merged**
